var Nombre = prompt("Ingrese Nombre");
var Direccion = prompt("Ingrese Direccion");
var Telefono = prompt(" Ingrese Telefono");
var Email = prompt("ingrese Correo ");
var Edad = prompt("ingrese su Edad");
alert(
  `Mi nombre es ${Nombre},\nMi edad es ${Edad}, \nMi telefono es ${Telefono},\nMi dirección es ${Direccion}, \nMi correo es ${Email}`
);
console.log(
  `Mi nombre es ${Nombre},\nMi edad es ${Edad}, \nMi telefono es ${Telefono},\nMi dirección es ${Direccion}, \nMi correo es ${Email}`
);
//las Comillas las comillas Bastick se pueden hacer para citar varios comentarios con \n se realiza saltos de linea.
// las comillas se obtiene con alt + 96 y se hace asi alert(`Mi nombre es ${nombre}, mi edad es ${edad}, mi telefono es${tel}`)//
